### ISSUE TITLE
Marcação não aparece no labelImg

### ISSUE THREAD

**Issue by erickotsuka** [ThundeRatz/labelling-web-app#4]
O arquivo: 4_z8126b7d060d92d74599e0618_f1194d872661f0a2f_d20161224_m035118_c001_v0001037_t0013.xml
contém coordenadas mas não aparece a marcação no labelImg.

**Comment by erickotsuka** [comment]
No arquivo parecem ter duas labels, mas na imagem só tem um cone.

**Comment by tiagoshibata** [comment]
Pode upar o XML? Ele apaga da tabela de novas labels do DB quando alguém faz download.

**Comment by tiagoshibata** [comment]
Ping @erickotsuka

**Comment by erickotsuka** [comment]
[voc-labels.zip](https://github.com/ThundeRatz/labelling-web-app/files/743696/voc-labels.zip)
Upar aqui no git não suportava xml, então zipei todas e mandei como zip. É o com o ID que falei acima que está com problema.
